-- ============================================================
-- Asystent Osobisty AI — Database Schema (PostgreSQL / Neon)
-- Interface Contract — single source of truth
-- Generated by: Agent 4A (Tech Foundation)
-- Used by: Agent 4B (Dev), Agent 5B (Audit)
--
-- RULE: Agent 4B must implement migrations that match this schema.
-- Any deviation requires an ADR entry in decisions_log.md.
-- ============================================================
-- Naming: snake_case tables (plural), snake_case columns
-- PKs: UUID with gen_random_uuid()
-- Timestamps: created_at, updated_at on every table
-- Multi-tenancy: Row-level (user_id FK on every app table)
-- ============================================================

-- AUTH TABLES (managed by better-auth) -----------------------

CREATE TABLE users (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  email         TEXT NOT NULL UNIQUE,
  email_verified BOOLEAN NOT NULL DEFAULT false,
  image         TEXT,
  phone         TEXT,
  role          TEXT NOT NULL DEFAULT 'user',   -- 'admin' | 'user'
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token         TEXT NOT NULL UNIQUE,
  expires_at    TIMESTAMPTZ NOT NULL,
  ip_address    TEXT,
  user_agent    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_token ON sessions(token);

CREATE TABLE accounts (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  account_id                TEXT NOT NULL,
  provider_id               TEXT NOT NULL,
  access_token              TEXT,
  refresh_token             TEXT,
  access_token_expires_at   TIMESTAMPTZ,
  refresh_token_expires_at  TIMESTAMPTZ,
  scope                     TEXT,
  password                  TEXT,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_accounts_user_id ON accounts(user_id);

-- PASSKEYS (WebAuthn / biometric login) ----------------------

CREATE TABLE passkeys (
  id              TEXT PRIMARY KEY,
  name            TEXT,
  public_key      TEXT NOT NULL,
  user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  credential_id   TEXT NOT NULL UNIQUE,
  counter         INTEGER NOT NULL DEFAULT 0,
  device_type     TEXT,
  backed_up       BOOLEAN DEFAULT false,
  transports      TEXT,
  aaguid          TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_passkeys_user_id ON passkeys(user_id);
CREATE INDEX idx_passkeys_credential_id ON passkeys(credential_id);

-- CONVERSATIONS & MESSAGES -----------------------------------

CREATE TABLE conversations (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title         TEXT NOT NULL DEFAULT 'Nowa rozmowa',
  summary       TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_conversations_user_id ON conversations(user_id);
CREATE INDEX idx_conversations_updated_at ON conversations(updated_at);

CREATE TABLE messages (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id   UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role              TEXT NOT NULL,             -- 'user' | 'assistant' | 'system'
  content           TEXT NOT NULL,
  source_type       TEXT,                      -- 'rag' | 'web' | 'ai' | 'memory' | 'tool'
  source_metadata   JSONB,
  token_count       INTEGER,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX idx_messages_created_at ON messages(created_at);

-- DOCUMENTS & RAG --------------------------------------------

CREATE TABLE documents (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  mime_type     TEXT NOT NULL,
  size_bytes    INTEGER NOT NULL,
  blob_url      TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'processing',  -- 'processing' | 'ready' | 'error'
  chunk_count   INTEGER DEFAULT 0,
  error_message TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_documents_user_id ON documents(user_id);
CREATE INDEX idx_documents_status ON documents(status);

CREATE TABLE document_chunks (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id     UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  chunk_index     INTEGER NOT NULL,
  content         TEXT NOT NULL,
  embedding       TEXT NOT NULL,      -- stored as text, cast to vector(1024) in queries
  page_number     INTEGER,
  section_title   TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_chunks_document_id ON document_chunks(document_id);
-- NOTE: pgvector index created via raw SQL migration:
-- CREATE INDEX idx_chunks_embedding ON document_chunks
--   USING ivfflat (embedding::vector(1024) vector_cosine_ops);

-- LONG-TERM MEMORY -------------------------------------------

CREATE TABLE memories (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content                   TEXT NOT NULL,
  category                  TEXT NOT NULL DEFAULT 'general', -- 'preference' | 'fact' | 'context' | 'general'
  embedding                 TEXT,
  source_conversation_id    UUID REFERENCES conversations(id) ON DELETE SET NULL,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_memories_user_id ON memories(user_id);

-- NOTIFICATIONS ----------------------------------------------

CREATE TABLE notifications (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content         TEXT NOT NULL,
  scheduled_at    TIMESTAMPTZ NOT NULL,
  recurrence      TEXT NOT NULL DEFAULT 'once',   -- 'once' | 'daily' | 'weekly' | 'monthly'
  is_active       BOOLEAN NOT NULL DEFAULT true,
  next_send_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);

CREATE TABLE notification_logs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  notification_id   UUID NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
  status            TEXT NOT NULL,      -- 'sent' | 'failed' | 'retrying'
  error_message     TEXT,
  attempt_number    INTEGER NOT NULL DEFAULT 1,
  sent_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notification_logs_notification_id ON notification_logs(notification_id);
