/**
 * Asystent Osobisty AI — Shared TypeScript Types
 * Interface Contract — single source of truth
 * Generated by: Agent 4A (Tech Foundation)
 * Used by: Agent 4B (Dev — frontend & backend must import from here)
 *
 * RULE: Both frontend and backend reference these types.
 * Agent 4B NEVER redefines types locally — always imports from this file.
 * Any change requires an ADR entry in decisions_log.md.
 *
 * ACTUAL IMPLEMENTATION: src/types/index.ts (mirrors this contract)
 */

// ---- Base Types ---------------------------------------------
export type UUID = string;
export type ISODateString = string;

export interface Timestamps {
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

// ---- Enums --------------------------------------------------
export type UserRole = "admin" | "user";
export type MessageRole = "user" | "assistant" | "system";
export type SourceType = "rag" | "web" | "ai" | "memory" | "tool";
export type DocumentStatus = "processing" | "ready" | "error";
export type MemoryCategory = "preference" | "fact" | "context" | "general";
export type NotificationRecurrence = "once" | "daily" | "weekly" | "monthly";
export type NotificationLogStatus = "sent" | "failed" | "retrying";

// ---- Domain Types -------------------------------------------
export interface User extends Timestamps {
  id: UUID;
  name: string;
  email: string;
  emailVerified: boolean;
  image: string | null;
  phone: string | null;
  role: UserRole;
}

export interface Conversation extends Timestamps {
  id: UUID;
  userId: UUID;
  title: string;
  summary: string | null;
}

export interface Message {
  id: UUID;
  conversationId: UUID;
  role: MessageRole;
  content: string;
  sourceType: SourceType | null;
  sourceMetadata: SourceMetadata | null;
  tokenCount: number | null;
  createdAt: ISODateString;
}

export interface SourceMetadata {
  documents?: Array<{
    name: string;
    pageNumber?: number;
    sectionTitle?: string;
  }>;
  urls?: string[];
  tools?: string[];
}

export interface Document extends Timestamps {
  id: UUID;
  userId: UUID;
  name: string;
  mimeType: string;
  sizeBytes: number;
  blobUrl: string;
  status: DocumentStatus;
  chunkCount: number;
  errorMessage: string | null;
}

export interface Memory extends Timestamps {
  id: UUID;
  userId: UUID;
  content: string;
  category: MemoryCategory;
  sourceConversationId: UUID | null;
}

export interface Notification extends Timestamps {
  id: UUID;
  userId: UUID;
  content: string;
  scheduledAt: ISODateString;
  recurrence: NotificationRecurrence;
  isActive: boolean;
  nextSendAt: ISODateString | null;
}

// ---- API Request Types --------------------------------------
export interface SendMessageRequest {
  conversationId: UUID;
  content: string;
}

export interface CreateNotificationRequest {
  content: string;
  scheduledAt: ISODateString;
  recurrence?: NotificationRecurrence;
}

export interface UpdateNotificationRequest {
  content?: string;
  scheduledAt?: ISODateString;
  recurrence?: NotificationRecurrence;
  isActive?: boolean;
}

// ---- API Response Types -------------------------------------
export interface ConversationListItem {
  id: UUID;
  title: string;
  updatedAt: ISODateString;
  lastMessagePreview: string | null;
}

export interface ConversationWithMessages {
  conversation: Conversation;
  messages: Message[];
}

export interface DocumentListItem {
  id: UUID;
  name: string;
  mimeType: string;
  sizeBytes: number;
  status: DocumentStatus;
  chunkCount: number;
  createdAt: ISODateString;
}

export interface MemoryListItem {
  id: UUID;
  content: string;
  category: MemoryCategory;
  createdAt: ISODateString;
}

export interface NotificationListItem {
  id: UUID;
  content: string;
  scheduledAt: ISODateString;
  recurrence: NotificationRecurrence;
  isActive: boolean;
  nextSendAt: ISODateString | null;
}

// ---- API Error Type -----------------------------------------
export interface ApiError {
  error: {
    code: string;
    message: string;
    details?: Record<string, unknown>;
  };
}

export type ErrorCode =
  | "VALIDATION_ERROR"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "RATE_LIMITED"
  | "FILE_TOO_LARGE"
  | "UNSUPPORTED_FILE_TYPE"
  | "PROCESSING_ERROR"
  | "AI_ERROR"
  | "SEARCH_ERROR"
  | "NOTIFICATION_ERROR"
  | "INTERNAL_ERROR";
